### ISSUE TITLE
rpm: docsis tool build own rpm

### ISSUE THREAD

**Issue by Gitrosa** [nmsprime/nmsprime#319]
<ul>
	<li>has to be compiled</li>
	<li>to build use fpm package</li>
</ul>

<p>fpm -s dir -t rpm -v $version --description "$descr" $options $build_opt $exclude -n nms-base $dir_base=/var/www/ $files $dir_rpm/mysql=/var/www/admin/install/mysql</p>
<i>[LAR-12] created by @schmto</i>

**Comment by schmto** [comment]
@olebowle solved this here: https://repo.roetzer-engineering.com/rpm/nmsprime/docsis-0.9.8.r391.g6b23fd2-1.x86_64.rpm
