### ISSUE TITLE
RPM: strategy for database changes

### ISSUE THREAD

**Issue by Gitrosa** [nmsprime/nmsprime#358]
<ul class="alternate" type="square">
	<li>automatic rpm scripts should run migrate and php artisan nms:auth</li>
</ul>

<ul class="alternate" type="square">
	<li>keep a automatic security update of entire database</li>
</ul>

<i>[LAR-54] created by @schmto</i>

**Comment by schmto** [comment]
solved by @olebowle and @schmto in Oct 2017
