### ISSUE TITLE
RPM: add a MVC for online automatic license installation

### ISSUE THREAD

**Issue by Gitrosa** [nmsprime/nmsprime#360]
<ul class="alternate" type="square">
	<li>One SQL / Eloquent Entry per Module</li>
	<li>Fields should be: id, name, license text, description, valid until, registered from, ..</li>
	<li>Update / Insert should update /etc/nms/license/...txt files</li>
	<li>MVC should automatically look before opening controller if<br/>
  some new modules have been installed or if modules have been deleted</li>
</ul>

<i>[LAR-56] created by @schmto</i>

**Comment by schmto** [comment]
deprecated by @schmto and partially solved and implemented by @NinoRy in version 2.4
