### ISSUE TITLE
Billing: cancel of Contract should automatically generate "letter of resignation"

### ISSUE THREAD

**Issue by Gitrosa** [nmsprime/nmsprime#441]
<p>Wunsch</p>

<p>Edit Nino: letter should not really be automatically generated, but like the creation of connection infos - therefore we should:</p>
<ul>
	<li>extend the "create conn infos" page and rename it to sth like "Letters", where you can download all sorts of letters a customer can get some day (just remember the meeting with enso in Dresden)</li>
</ul>

<i>[LAR-138] created by @schmto</i>

**Comment by NinoRy** [comment]
Adressed in https://github.com/nmsprime/nmsprime/issues/565

**Comment by NinoRy** [comment]
Addressed in https://github.com/nmsprime/nmsprime/issues/565
