### ISSUE TITLE
Authuser silently changing password

### ISSUE THREAD

**Issue by Gitrosa** [nmsprime/nmsprime#444]
<p>While typing the password for my devel NMS manually I have stored the password for the devel database in my firefox – both users are called the same.</p>

<p>Changing the language in /lara/admin/Authuser/1/edit automatically changes the password to the database password – filled in this field by FF. Until I figured out I were locked out…</p>

<p>IMO at least a change of the password should require the old password to be given.</p>
<i>[LAR-141] created by @xee8ai</i>

**Comment by schmto** [comment]
@cschra : any further ideas?

**Comment by cschra** [comment]
fixed already by the new auth system #322  ... 
passwords now need to be confirmed, when password is empty it is not changed
only feature would be to give the password field a property to prevent Autofill - this would be a small fix. If this should be implemented, pm me.
