### ISSUE TITLE
CCC: test GUI with actual test branch

### ISSUE THREAD

**Issue by Gitrosa** [nmsprime/nmsprime#463]
<p>please test stuff like:</p>
<ul>
	<li>like changing password (etc) from CCC and admin site,</li>
	<li>downloading invoices and CDRs  from CCC and admin site</li>
	<li>cross-check security stuff in CCC: Could there be any changes which be critical and need re-testing? e.g. BaseController, Auth, changes ...</li>
</ul>

<p> </p>
<i>[LAR-162] created by @schmto</i>

**Comment by cschra** [comment]
done in #236 and #170
