### ISSUE TITLE
Billing/Dashboard: Quick-view for new customers

### ISSUE THREAD

**Issue by Gitrosa** [nmsprime/nmsprime#475]
<p>Show a Quick-view – like active contracts – on Dashboard, like e.g.</p>

<p>New Customer (Day/Week/Month/Year): 1/5/15/100</p>

<p>Im not quit sure how to handle contracts quitting in this intervals. For coding style IMHO it will be great to reuse the function from <a href="https://devel.roetzer-engineering.com/jira/secure/ViewProfile.jspa?name=sven.arndt" class="user-hover" rel="sven.arndt">Sven Arndt</a> for contract analysis blade.</p>
<i>[LAR-180] created by @schmto</i>

**Comment by schmto** [comment]
solved here: https://github.com/nmsprime/nmsprime/pull/293
