### ISSUE TITLE
Date: Function, enable german format and/or calendar

### ISSUE THREAD

**Issue by Gitrosa** [nmsprime/nmsprime#477]
<p>Some request:</p>
<ul class="alternate" type="square">
	<li>german date format, like 01.12.2017</li>
	<li>or calendar plugin from (JS)</li>
</ul>

<p>There must be some kind of global switching between which date format we use</p>
<i>[LAR-182] created by @schmto</i>

**Comment by cschra** [comment]
Datefields are used across the system now
