### ISSUE TITLE
Auth-Probleme in NMS Prime

### ISSUE THREAD

**Issue by Gitrosa** [nmsprime/nmsprime#487]
<p>Folgend nochmal der Text meiner Mail (ich bin zu faul, dass nochmal auf Englisch zu formulieren):</p>

<p>Nino wies mich darauf hin, dass sich aktuell jeder Nutzer Rollen zuweisen und damit zum Superuser werden kann. Ich habe jetzt bemerkt, dass jeder Nutzer mit create/edit-Rechten auf authuser (nötig z.B. für das Ändern des eigenen Passworts) auch alle anderen Nutzer sehen/ändern (z.B. Passwort, Rollen) kann (und damit z.B. alle außer sich selbst vom System aussperren). Dazu muss nur die ID in der Authuser-edit-URL entsprechend ersetzt werden.</p>
<i>[LAR-192] created by @xee8ai</i>

**Comment by cschra** [comment]
yes
