### ISSUE TITLE
Collective ticket for bugs after switch to Laravel 5.3

### ISSUE THREAD

**Issue by Gitrosa** [nmsprime/nmsprime#493]
<p>There are some issues after after switching to Laravel 5.3. This ticket collects them to avoid fixing bugs multiple times by different devs.</p>

<p>Just add subtickets for each issue.</p>

<p> </p>

<p>@christian</p>

<p>@nino</p>

<p>@ole</p>
<i>[LAR-198] created by @xee8ai</i>

**Comment by cschra** [comment]
could this be closed? @schmto @NinoRy @xee8ai @olebowle
