### ISSUE TITLE
Small improvements

### ISSUE THREAD

**Issue by Gitrosa** [nmsprime/nmsprime#501]
- [ ] Deutsch Übersetzung
	Modem Analysis –> Proximity Search
	Ticketsystem übersetzen
        Show customer in rectangle/ Show customer in polygon

- [x] Tabs geht rückwärts nicht von Diagramm, Topo, Controlling, Diagrams wird nicht immer von allen TABs rückwärts angezeigt
	Tabs fehlen von Vorderseite, z.B. auf https://nms10.erznet.tv:8080/admin/NetElement/31/diagram
	Tabs von Modemseite auf MTA

- [x] Beim anlegen eines Tickets sollte eine Mail geschickt werden an Assigned Users

- [ ] @cschra: On-Hover bei Modem Bubble geht nicht mehr

- [ ] artisan command zum Finden "veralteter" Modems über Cacti, danach Liste an Support mit Löschauftrag
	Google: "rrdtool show last online" oder ähnliches
	siehe Ordner /usr/share/cacti/rra/
	Am Ende reicht Ausgabe von cm-
	Ideal wäre Übergabeparameter mit Modem war mindestend seit <Datum> nicht online

- [x] Generic SNMP Module: add designs like
	Slider
	Traffic Lights based on Integer == <defined value>

<i>[LAR-206] created by @schmto</i>

**Comment by cschra** [comment]
-> "On-Hover bei Modem Bubble geht nicht mehr" is a known bug as of #403

**Comment by schmto** [comment]
@royschn : could you please mark the task which are done/open?
