### ISSUE TITLE
Fix Translations for salutation and academic degree

### ISSUE THREAD

**Issue by cschra** [nmsprime/nmsprime#542]
In ModemController, Contractcontroller, Phonenumbermanagement we use the method get_salutation_options and get academic_degree_options.
These function should return the translated salutation and academic degree but only contain German values.

**Comment by xee8ai** [comment]
Solved in v2.5.1.
Salutation and academic degree are freely configurable now (using textfiles in /var/www/nmsprime/storage/app/config/provbase/formoptions). No translations needed.

As envia TEL expects certain values this is deactivated if ProvVoipEnvia is enabled.
