### ISSUE TITLE
Fixes for ACS

### ISSUE THREAD

**Issue by schmto** [nmsprime/nmsprime#557]
- [x] @royschn toggling device after right click in topography does not work in 2.4.2. Actually it seems to work in here: https://github.com/nmsprime/nmsprime/commits/d7c6be7b1f7a1efc74ad9ba58db8e5e143e88dc7

- [x] Address Geocoding does not work for Neustaedter Str, Hummelshain. Seems to be a problem with missing zip code or city in the request towards google or OSM?

- [x] @royschn Google Satellite card is throwing a error: "This page can't load Google Maps correctly." and the map is shown with "development purpose only". Maybe we need a valid registration for that?

- [x] @royschn modem analysis page optimization at smartphones. The graph section with cacti diagrams is loaded correctly, but we can not move to the right, to see the graphs on the right side. There are two possible ways to address this: A) add a scrollbar to the cacti frame B) if loaded in smartphone context, just load 1 image at a row

- [x] @royschn Optimize modem analysis page at iPad's (see screenshot Torsten from Angel 26.11)

- [x] @olebowle Modem Analysis: show Modem Overview diagram first

- [x] @royschn Impaired Services: add a second link (next to icinga), which will directly link to the NetElement Controlling page, if available

- [x] @royschn Add a Traffic Light to ORA and VGPs. This should be addressed in some other ticket as well 

NOTE: most of the stuff should be solved until KW1 of 2019

**Comment by olebowle** [comment]
Modem Analysis: show Modem Overview diagram first --> fixed in 88f3999

**Comment by olebowle** [comment]
add second (controlling) link --> fixed in 8bfa23d

**Comment by royschn** [comment]
analysis page for iPads --> fixed in [deefd44](url)

**Comment by royschn** [comment]
Google Satellite error --> fixed in [6c2049d](url)

**Comment by royschn** [comment]
Form traffic light --> added in 3ce306e

**Comment by olebowle** [comment]
All issues have been resolved! :+1:
