### ISSUE TITLE
NMS PRIME TODOs for Datel

### ISSUE THREAD

**Issue by schmto** [nmsprime/nmsprime#558]
Fast requirements
- [x] @royschn Modem –> pingable () return json online (1) or offline (0)
   admin/api/v{ver}/Modem/{Modem}/pingable

TODOs
- [x] modem/mta neustarten via API
   admin/api/v{ver}/Modem/{Modem}/reboot or restart
   (..)

@cschra: 
- [x] password hinweis + nutzer zwingen passwort zu ändern
- [x] neue rolle selbst zuweisen möglich???
- [x] readonly rolle
- [x] Modem/MTA Analysis page should be able to be displayed without having write access

**Comment by olebowle** [comment]
pingable: fixed in 6897128
restart: fixed in af58144
