### ISSUE TITLE
ACS fixes from 2019-january

### ISSUE THREAD

**Issue by schmto** [nmsprime/nmsprime#591]
- [x] Contract Index Page Color:
Internet Access disabled + VoIP only active = Contract line should be green 

- [x] Disable "Create Connection Info" button if CCC & Billing is disabled

- [x] modem analysis page: show warning message in dashboard if network access if disabled

- [x] add env variable or global settings for setting: open modem in topography in new tab

- [ ] modem edit page: add proximity search with a drop down menu (e.g. 50, 100m, 250m, 500m) near modem position

**Comment by NinoRy** [comment]
proximity search was added to analysis page
