### ISSUE TITLE
DPOE v2 TLV support

### ISSUE THREAD

**Issue by qaggaz** [nmsprime/nmsprime#594]
**Is your feature request related to a problem? Please describe.**
DPOE TLVs are currently not support in the config file.

**Describe the solution you'd like**
I would like to be able to support configuration files like the following for a MEF ELINE service defined on a Nokia 7360 with Docsis Provisioning of EPON support (Ideally the hex field for RouteDistinguisher and the RouteTargets could also be parsed so that the hex string below could appear as 8047:10001):
 
        NetworkAccess 1;
        GlobalPrivacyEnable 1;
        MaxCPE 16;
        VendorSpecific
        {
                VendorIdentifier 0xffffff;
                L2VPNEncoding
                {
                        L2VPNIdentifier "vpls10001";
                        L2VPNMode 0;
                        BgpAttribute
                        {
                                BgpVpnId 10001;
                                RouteDistinguisher 0x00001f6f00002711;
                                RouteTargetImport 0x00021f6f00002711;
                                RouteTargetExport 0x00021f6f00002711;
                        }
                        L2VpnSg "l2vpn-1";
                }
        }
        UsServiceFlow
        {
                UsServiceFlowRef 1;
                QosParamSetType 7;
                MaxRateSustained 1000000000;
                MinReservedRate 500000000;
                SchedulingType 4;
                NominalPollInterval 1000;
                VendorSpecific
                {
                        VendorIdentifier 0xffffff;
                        L2VPNEncoding
                        {
                                L2VPNIdentifier "vpls10001";
                        }
                }
        }
        DsServiceFlow
        {
                DsServiceFlowRef 100;
                QosParamSetType 7;
                MaxRateSustained 1000000000;
                MinReservedRate 500000000;
        }
        UsPacketClass
        {
                ClassifierRef 1;
                ServiceFlowRef 1;
                RulePriority 0;
                CMInterfaceMask 0x40000000;
 
        }
        DsPacketClass
        {
                ClassifierRef 100;
                ServiceFlowRef 100;
                RulePriority 0;
                VendorSpecific
                {
                        VendorIdentifier 0xffffff;
                        L2VPNEncoding
                        {
                                L2VPNIdentifier "vpls10001";
 
                        }
                }
        }

**Describe alternatives you've considered**
n/a

**Additional context**
the above configuration builds a MEF ELAN service across all vCMs on a single OLT/vCMTS, as well as extending an MPLS VPLS instance to other Nodes using BGP-Autodiscovery.

I would like to be able to use nmsprime to deploy services like this on DPOEv2 compliant EPON nodes.

**Comment by NinoRy** [comment]
Hi,
i think this issue should be addressed at the docsis tool (see https://github.com/rlaager/docsis) as it is the tool we are using to build the configfiles. I don't know why e.g. L2VPNIdentifier is missing in https://github.com/rlaager/docsis/blob/master/src/docsis_symtable.h. Maybe you can open a pull request there!?

**Comment by cschra** [comment]
closed due to inactivity.
