### ISSUE TITLE
Discrepancy while adding billing Item via API

### ISSUE THREAD

**Issue by dabuechler** [nmsprime/nmsprime#620]
I discovered that when one adds a product to a contract via API, the valid_from field is always set to the next day.  When one adds a product to a contract via the web interface, the valid_from field is always the same day.  It doesn't seem to matter if the valid_from date is specified in the create request or not.

**Comment by olebowle** [comment]
I assume you are talking about adding an Internet item. As you can see via the WebGUI when creating an Item both `valid_from_fixed` and `valid_to_fixed` are set to `1`. If you do the same via the API you should also get the same date in `valid_from`, namely today:

```
session.post('https://localhost:8080/admin/api/v0/Item', json={'contract_id' : 500000, 'product_id' : 42, 'count' : 1, 'valid_from_fixed' : 1, 'valid_to_fixed' : 1}, verify=False)
```

**Comment by olebowle** [comment]
Closing the issue for now. If you still encounter the problem please reopen the issue.
