### ISSUE TITLE
Dependency Issue related to install NMSPrime in RHEL 7.6 Server

### ISSUE THREAD

**Issue by vaghelarajeshh** [nmsprime/nmsprime#635]
![image](https://user-images.githubusercontent.com/19392215/54954110-42d03580-4f20-11e9-9508-feb7ac49ef00.png)

I have tried various option to resolve this issue. I am not able to figure out to resolve the dependencies. It may point to bug in the coding or initialization.

I did as per the procedure in installing nmsprime.

**Comment by schmto** [comment]
Hey @vaghelarajeshh, thanks for opening this issue. We will come back to you soon. nmsprime 2.4.4 is released 17 hours ago. Do you have the same issue using nmsprime 2.4.3? IMHO: you could test this using 
`yum install nmsprime-*2.4.3*`. 
@olebowle will come back to you soon.

**Comment by olebowle** [comment]
Hi,

please notice that we recommend using CentOS, thus RHEL has not been tested. However, as they are functionally compatible it should work as well.

You need to run `yum-config-manager --enable rhel-server-rhscl-7-rpms` on RHEL to enable [Software Collections](https://www.softwarecollections.org/en/scls/rhscl/rh-php71/) which is needed for using PHP7.1. Afterwards the dependencies should be met and you should be able to install the nmsprime packages.

I suppose this is a new installation and not an update?

**Comment by vaghelarajeshh** [comment]
Hi,


This is the new installation. I do understand the CentOs and RHEL are using
the same packages except the Software collection. I have enabled to get
software. Even I tried to install PHP 71/72 to make these two packages
enable. But somehow, it is not accepting this.



*Thanks and Regards,*

*Vaghela Rajesh*
*skype: vaghelarajesh*
*+1 647-770-2694*

**Comment by olebowle** [comment]
Can you please try: https://access.redhat.com/discussions/3232341#comment-1237801

**Comment by vaghelarajeshh** [comment]
Thanks  Ole,


I have installed NMSPrime.

I can do web ui to localhosts.

**Comment by olebowle** [comment]
Cool so the issue is resolved, have fun with NMSPrime!
