### ISSUE TITLE
Performance Improvement

### ISSUE THREAD

**Issue by NinoRy** [nmsprime/nmsprime#648]
1. Implement join statements to our ajax datatables functionality
** Fetch data e.g. Product in Item::view_has_many() with join and select only relevant data to reduce creation of eloquent instances and reduce time of page load

2. As view_has_many already loads all relations changing the tabs on the index pages should not force a page reload - instead just fade in & out the panels.

**Comment by cschra** [comment]
closed as this is now topic of #688
