### ISSUE TITLE
property management

### ISSUE THREAD

**Issue by olebowle** [nmsprime/nmsprime#654]
- [x] Add new module
- [ ] Add MVCs 'Property' and 'Flat' with following relations:
* Property ---> Flat ---> Modem
* Property ---> Flat ---> Contract
* Property ---> Contract
- Property must have minimum these colums:
* Owner
* (technical) construction - for content like 'FTTH' / 'Copper' / 'HFC' / ...

- [ ] Implement assigning an apartment number to a contract
- [x] Implement a view showing all apartments having the same address -> index view should be sufficient
- [ ] Implement setting a contract to be used by a single individual or a group of people
- [ ] Thus, allowing us to bill group contracts

**Comment by cschra** [comment]
#735
