### ISSUE TITLE
state of column visibility in index table

### ISSUE THREAD

**Issue by NinoRy** [nmsprime/nmsprime#679]
die spaltensichtbarkeit sollte gespeichert werden. Wird irgendwie nach einer Zeit wieder zurück gesetzt und ich sehe wieder alle spalten

**Comment by cschra** [comment]
Die Spaltensichtbarkeit wird im local Storage des Browsers gespeichert. Das heißt bei löschen des Browsercaches geht auch diese Einstellung verloren.

**Comment by cschra** [comment]
Allerdings hat Datatables eine Interne Logik, die 2h alte Änderungen verwirft. Bei jeder Änderung (auch Suche) am local Storage wird die Zeit geupdated. [Hier](https://datatables.net/forums/discussion/35082/local-storage-expiration) ist ein Forumthread in dem Beschrieben wird, dass eine "StateDuration" gesetzt werden soll um das Standardverhalten zu verändern.
