### ISSUE TITLE
Update to Laravel 5.4

### ISSUE THREAD

**Issue by cschra** [nmsprime/nmsprime#692]
This is a collection for issues with the Laravel 5.4 Upgrade. Reference this issue, to keep track of all Bugs and changes correlating with Laravel 5.4.

**Comment by cschra** [comment]
PR #694 is opened and after merge, bugs related to the upgrade can be referenced and discussed here

**Comment by cschra** [comment]
- [ ] id field in GUI-Log needs to be a raw column

**Comment by NinoRy** [comment]
Envia-Order Index Table URLs are plain html text / not escaped
