### ISSUE TITLE
Introduce speedtest files on the provisioning server

### ISSUE THREAD

**Issue by olebowle** [nmsprime/nmsprime#705]
In order to test download speeds within the provider network, sparse speedtest files should be created on the provisioning server, which can be downloaded by a customer.

These files should only be downloadable by a logged in customer to avoid downloads from the outside world, which would generate uplink traffic for the provider.

The open branch [feature/speedtest](https://github.com/nmsprime/nmsprime/tree/feature/speedtest) is a good starting point.

**Comment by olebowle** [comment]
Better yet, we should use: [speedtest](https://github.com/adolfintel/speedtest)

**Comment by cschra** [comment]
Implemented with #775
