### ISSUE TITLE
Modem picture on Analyses page

### ISSUE THREAD

**Issue by NinoRy** [nmsprime/nmsprime#737]
- [x] Show picture in Modem Analyses page
- [x] Picture should be shipped with our package and be stored in storage directory and within GIT
  * The question is still where we can get all the pictures from - could probably be downloaded from https://icecat.co.uk/ without any license issues

**Comment by olebowle** [comment]
- [ ] another source might be https://www.speedguide.net/broadband.php (inquiry ongoing)

**Comment by olebowle** [comment]
[] we should get in contact with more vendors asking to deploy their images
