### ISSUE TITLE
Small Adds for v2.6

### ISSUE THREAD

**Issue by NinoRy** [nmsprime/nmsprime#807]
PropertyManagement: Ticket must belong to contact, apartment, realty (they can have many tickets)
* [x] add columns (ticket needs contact_id, apartment_id, realty_id)
* [x] add relations
* [x] add panels to each models edit page

Product
* [x] ausblenden in item select list, wenn veraltet
	* like in configfile 'public use'

Ticket
* [x] alle Kontaktdaten in separatem Panel (Vertrag)
     ** Email, Adressen, Telefon
* [x] Zeilenumbruch im Ticket muss funktionieren
* [x] Email an Nutzer, der aus Ticket entfernt wird, muss Link zum Ticket enthalten
* Indextabelle: 
  * [x] Kundennr, Vorname, Nachname, Straße, Hausnummer, PLZ, Ort, Ortsteil hinzufügen
  * [x] nach Tickettyp sortieren knallt

Modem + NetGw
* [x] in view_index_label wird der SLA geprüft und dabei jedesmal eine DB Abfrage durchgeführt. Das macht die Index-Tabelle unheimlich langsam und auch den Contract page load wegen den relations --> die Prüfung sollte beim Login 1x in die session geschrieben und dann immer von dort geholt werden - implemented in 9c962b4

**Comment by cschra** [comment]
Remove duplicate Queries in different Locations of the Application
 -> use barryvdh/laravel-debugbar to see which queries run and if there are duplications
-> I checked the Index Pages and ERD Pages -> todo would be to look into edit/create pages.

- [ ] MibFile has 24+ queries just counting oids -> use withCount...
- [ ] Global Config Page has some duplicate queries
- [ ] Tree View is very query intensive, especially configfile and netelementtype (needs heavy adjustments to logic)

**Comment by NinoRy** [comment]
closed and moved @cschra 's comments to https://github.com/nmsprime/nmsprime/issues/885
