### ISSUE TITLE
Small fixes v2.5.x

### ISSUE THREAD

**Issue by NinoRy** [nmsprime/nmsprime#818]
- [x] Provisioning Dashboard -> quickstart panel Create NetGw is not translated -> see modules/ProvBase/Resources/view/widgets/quickstart.blade.php

**Comment by NinoRy** [comment]
@royschn @olebowle @schmto @cschra @xee8ai Maybe we can just collect all small issues (like missing translations etc) here that appear by rolling out v2.5.0

**Comment by cschra** [comment]
#820 fixes GuiLog Error on non-soft-deleting models
