### ISSUE TITLE
Implement ticket relations as polymorphic one-to-many

### ISSUE THREAD

**Issue by NinoRy** [nmsprime/nmsprime#886]
see comment of https://github.com/nmsprime/nmsprime/pull/837/commits/235203090184082c171d6678b1c09d60656ece56

"this might be the perfect use case for a [Polymorphic One to Many](https://hackernoon.com/eloquent-relationships-cheat-sheet-5155498c209) relationship. [Laravel](https://laravel.com/docs/5.5/eloquent-relationships#polymorphic-relations) has a good documentation on this."

- [ ] new table: ticket_to_model
  * [ ] columns: model_id, model, ticket_id
- [ ] extend store function in a generic way
- [ ] fetch select values dependent of selected model via ajax to not overload browser

models (types): contract, user (creator), apartment, contact, realty, ... (can become more)

**Comment by cschra** [comment]
implemented
