### ISSUE TITLE
Installation Dependency error

### ISSUE THREAD

**Issue by fisnnik** [nmsprime/nmsprime#895]
steps that i followed:
curl -vsL https://raw.githubusercontent.com/nmsprime/nmsprime/master/INSTALL-REPO.sh | bash
yum install nmsprime-* --exclude nmsprime-billing

--> Finished Dependency Resolution
Error: Package: nmsprime-base-2.5.3-1.noarch (nmsprime)
           Requires: sclo-php71-php-mcrypt
Error: Package: icingaweb2-module-director-1.4.2-7.x86_64 (nmsprime)
           Requires: sclo-php71-php-pecl-imagick
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

 - Centos 7

![error-nmsprime](https://user-images.githubusercontent.com/50664136/79877342-68ae5f00-83ec-11ea-9fc1-76e2a34f069f.png)

I have tried to fix this in many ways but with no success!

**Comment by olebowle** [comment]
Hi, it seems both dependencies are not supplied anymore. We will remove those dependencies in the upcoming release. For now we included both packages in our repo. Thus, you should be able to install NMS Prime now.

**Comment by fisnnik** [comment]
Hi, thank for reply. I have installed NMSPRIME now, and everything looks fine until now.
