### ISSUE TITLE
Integration wirh other DHCP and CRM

### ISSUE THREAD

**Issue by aariza-argentina** [nmsprime/nmsprime#923]
Hi! Is it possible to ingtegrate with ohter DHCP and CRM?
We have all the APIs, with files or databases we have to looking for?
Thanks!
PD: Sorry for me enlgish

**Comment by NinoRy** [comment]
Hi. Everything is possible, but it needs a lot of self made adaptions to the PHP code of NMS Prime if you want to use another DHCP server.
But you can easily use your own CRM by connecting it to NMS Prime via our [API](https://devel.roetzer-engineering.com/confluence/display/NMS/API).

Please use our [official forum ](https://devel.roetzer-engineering.com/confluence/display/nmsprimeforum/Welcome) for this kind of questions.
