### ISSUE TITLE
Instalation error mongodb-server

### ISSUE THREAD

**Issue by qba89** [nmsprime/nmsprime#952]
New centos7 install (1908 and 2009) both kickstart and rpm install gives error: Package: genieacs-1.1.3-1.x86_64 (nmsprime)
           Requires: mongodb-server

**Comment by NinoRy** [comment]
It will be fixed in the next version

Until it's available there's a solution postet in our forum: https://devel.roetzer-engineering.com/confluence/display/nmsprimeforum/GenieACS+require+mongodb-server

**Comment by qba89** [comment]
Thank you very much. it worked for me. greetings
